[kafka]
debug = true
EnableAccessInterceptor = true
EnableAccessInterceptorReq = true
EnableAccessInterceptorRes = true
EnableCompress = true
# 50B
CompressLimit = 50
brokers = ["192.168.64.65:9091", "192.168.64.65:9092", "192.168.64.65:9093"]
[kafka.client]
timeout = "3s"
[kafka.producers.p1]        # 定义了名字为p1的producer
topic = "sre-infra-debug"  # 指定生产消息的topic
[kafka.consumers.c1]        # 定义了名字为c1的consumer
topic = "sre-infra-debug"  # 指定消费的topic
groupID = "group-0"       # 如果配置了groupID，将初始化为consumerGroup
